<!DOCTYPE html>
<html>

<head>
    <title>FactViewResearch</title>
</head>

<body>
    <p>Hello Admin,</p>
    <p>You have received an <strong>
            @if ($type == 'request')
                {{ 'REQUEST SAMPLE' }}
            @elseif($type == 'enquiry')
                {{ 'ENQUIRY BEFORE BUYING' }}
            @elseif($type == 'discount')
                {{ 'ASK FOR DISCOUNT' }}
            @endif
        </strong> enquiry from website.</p>
    <table style="border:1; border-collapse: collapse; width: 100%; height: 102px;">
        <tbody>
            <tr style="height: 17px;">
                <td style="width: 50%; height: 17px;">Report</td>
                <td style="width: 50%; height: 17px;"><a href="{{ $reportUrl }}" target="_blank">{{ $reportName }}</a>
                </td>
            </tr>
            <tr style="height: 17px;">
                <td style="width: 50%; height: 17px;">Contact No.</td>
                <td style="width: 50%; height: 17px;">{{ $contact_no }}</td>
            </tr>
            <tr style="height: 17px;">
                <td style="width: 50%; height: 17px;">Name</td>
                <td style="width: 50%; height: 17px;">{{ $name }}</td>
            </tr>
            <tr style="height: 17px;">
                <td style="width: 50%; height: 17px;">Email</td>
                <td style="width: 50%; height: 17px;">{{ $email }}</td>
            </tr>
            <tr style="height: 17px;">
                <td style="width: 50%; height: 17px;">Country</td>
                <td style="width: 50%; height: 17px;">{{ $country }}</td>
            </tr>
            <tr style="height: 17px;">
                <td style="width: 50%; height: 17px;">Company</td>
                <td style="width: 50%; height: 17px;">{{ $organizations }}</td>
            </tr>
            <tr>
                <td style="width: 50%;">Message</td>
                <td style="width: 50%;">{{ $others }}</td>
            </tr>
        </tbody>
    </table>
    <br />
    <p>Thank You,</p>
    <p>FactViewResearch</p>
    <p><em>This is autogenerated mail from website.</em></p>
</body>

</html>
